CREATE TABLE public.soundcloud_user (
    Id bigint NOT NULL,
    Title text NOT NULL,
    FirstName text NOT NULL,
    LastName text NOT NULL,
    FullName text NOT NULL,
    CountryCode text NOT NULL,
    City text NOT NULL,
    AvatarUrl text NOT NULL,
    PermaLink text NOT NULL,
    Url text NOT NULL,
    Urn text NOT NULL,
    Username text NOT NULL,
    Badge_ProUnlimited bool NOT NULL,
    Badge_Verified bool NOT NULL,
    LastModified timestamp,
    LastSyncTime timestamp DEFAULT current_timestamp,
    CONSTRAINT soundcloud_user_pkey PRIMARY KEY (Id)
);

CREATE TABLE public.soundcloud_track (
    Id bigint NOT NULL,
    UserId bigint NOT NULL,
    Title text NOT NULL,
    PlaylistName text NOT NULL,
    Caption text NOT NULL,
    Commentable bool NOT NULL,
    CommentCount int NOT NULL,
    Description text NOT NULL,
    Downloadable bool NOT NULL,
    DownloadCount bigint NOT NULL,
    Duration bigint NOT NULL,
    FullDuration bigint NOT NULL,
    EmbeddableBy text NOT NULL,
    Genre text NOT NULL,
    HasDownloadsLeft bool NOT NULL,
    LabelName text NOT NULL,
    License text NOT NULL,
    LikesCount bigint NOT NULL,
    Permalink text NOT NULL,
    PermalinkUrl text NOT NULL,
    PlaybackCount text NOT NULL,
    Public bool NOT NULL,
    PublisherMetadata_Artist text NOT NULL,
    PublisherMetadata_ContainsMusic bool NOT NULL,
    PublisherMetadata_Id text NOT NULL,
    PublisherMetadata_Urn text NOT NULL,
    PurchaseTitle text NOT NULL,
    PurchaseUrl text NOT NULL,
    ReleaseDate timestamp,
    RepostsCount bigint NOT NULL,
    Sharing text NOT NULL,
    State text NOT NULL,
    Streamable bool NOT NULL,
    TagList text NOT NULL,
    Uri text NOT NULL,
    ArtworkUrl text NOT NULL,
    Visuals text NOT NULL,
    WaveformUrl text NOT NULL,
    DisplayDate timestamp NOT NULL,
    MonetizationModel text NOT NULL,
    Policy text NOT NULL,
    Urn text NOT NULL,

    CreatedAt timestamp,
    LastModified timestamp,
    CONSTRAINT soundcloud_track_pkey PRIMARY KEY (Id, UserId)
);

CREATE TABLE public.soundcloud_track_transcoding (
    TrackId bigint NOT NULL,
    UserId bigint NOT NULL,
    Duration bigint NOT NULL,
    Preset text NOT NULL,
    Quality text NOT NULL,
    Snipped bool NOT NULL,
    FormatMimeType text NOT NULL,
    FormatProtocol text NOT NULL,
    CONSTRAINT soundcloud_track_transcoding_pkey PRIMARY KEY (TrackId, UserId, Duration, FormatMimeType, FormatProtocol)
);

CREATE TABLE public.soundcloud_playlist (
    Id bigint NOT NULL,
    UserId bigint NOT NULL,
    Title text NOT NULL,
    Description text NOT NULL,
    Duration bigint NOT NULL,
    EmbeddableBy text NOT NULL,
    Genre text NOT NULL,
    LabelName text NOT NULL,
    License text NOT NULL,
    LikesCount bigint NOT NULL,
    ManagedByFeeds bool NOT NULL,
    Public bool NOT NULL,
    PurchaseTitle text NOT NULL,
    PurchaseUrl text NOT NULL,
    ReleaseDate timestamp,
    RepostsCount bigint NOT NULL,
    Sharing text NOT NULL,
    TagList text NOT NULL,
    SetType text NOT NULL,
    IsAlbum bool NOT NULL,
    PublishedAt timestamp,
    TrackCount bigint NOT NULL,
    Uri text NOT NULL,
    PermalinkUrl text NOT NULL,
    Permalink text NOT NULL,
    ArtworkUrl text NOT NULL,
    DisplayDate timestamp NOT NULL,
    CreatedAt timestamp,
    LastModified timestamp,
    CONSTRAINT soundcloud_playlist_pkey PRIMARY KEY (Id, UserId)
);


CREATE TABLE public.soundcloud_playlist_track (
    UserId bigint NOT NULL,
    PlaylistId bigint NOT NULL,
    TrackId bigint NOT NULL,
    TrackOrder bigint NOT NULL,
    CONSTRAINT soundcloud_playlist_track_pkey PRIMARY KEY (UserId, PlaylistId, TrackId)
);